Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Max: 25
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FileName:
  Enabled: false
